---
# Project pre-commit configuration

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|yaml|yml|sh)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    # Otherwise will fail on commit-msg hook
    hooks:
      - id: prettier
        stages: [pre-commit]
        exclude: Pipfile.lock

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.0
    hooks:
      - id: markdownlint
        args: [--config, ".markdownlint.yaml"]
